package com.epam.infrastructure.controllers;

import com.epam.infrastructure.dtos.TraineeDto;
import com.epam.infrastructure.dtos.TraineeRegistrationRequest;
import com.epam.infrastructure.dtos.TraineeResponseDto;
import com.epam.infrastructure.dtos.TrainerBriefDto;
import com.epam.infrastructure.dtos.AuthDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;

@RequestMapping("/trainees")
@Tag(name = "Trainee Management", description = "CRUD operations for trainee profiles and their trainer assignments")
public interface TraineeController {

    @PostMapping
    @Operation(
            summary = "Register new trainee",
            description = "Creates a new trainee profile and returns autogenerated username and password.",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Trainee registration data",
                    required = true,
                    content = @Content(schema = @Schema(implementation = TraineeRegistrationRequest.class))
            ),
            responses = {
                    @ApiResponse(responseCode = "201", description = "Trainee successfully registered"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "400", description = "Invalid input data")
            }
    )
    ResponseEntity<AuthDto> register(@Valid @RequestBody TraineeRegistrationRequest trainee);

    @PutMapping
    @Operation(
            summary = "Update trainee profile",
            description = "Updates trainee personal information such as name, address, and activity state.",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Updated trainee information",
                    required = true,
                    content = @Content(schema = @Schema(implementation = TraineeDto.class))
            ),
            responses = {
                    @ApiResponse(responseCode = "200", description = "Profile updated successfully"),
                    @ApiResponse(responseCode = "404", description = "Trainee not found")
            }
    )
    ResponseEntity<TraineeResponseDto> updateProfile(@Valid @RequestBody TraineeDto trainee);

    @GetMapping("/{username}")
    @Operation(
            summary = "Get trainee profile",
            description = "Returns full profile information for a trainee.",
            parameters = @Parameter(
                    name = "username",
                    description = "Username of the trainee",
                    required = true
            ),
            responses = {
                    @ApiResponse(responseCode = "200", description = "Profile retrieved"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainee not found")
            }
    )
    ResponseEntity<TraineeResponseDto> getProfile(@PathVariable String username);

    @DeleteMapping("/{username}")
    @Operation(
            summary = "Delete trainee profile",
            description = "Deletes trainee profile permanently.",
            parameters = @Parameter(
                    name = "username",
                    description = "Username of trainee to delete",
                    required = true
            ),
            responses = {
                    @ApiResponse(responseCode = "204", description = "Profile deleted"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainee not found")
            }
    )
    ResponseEntity<Void> deleteProfile(@PathVariable String username);

    @GetMapping("/{username}/unassigned-trainers")
    @Operation(
            summary = "Get Active Trainers Not Assigned to a Trainee",
            description = "Retrieves a list of all active trainers who are not currently assigned to the specified trainee.",
            parameters = @Parameter(
                    name = "username",
                    description = "The username of the trainee for whom to fetch unassigned active trainers",
                    required = true
            ),
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successfully retrieved the list of unassigned active trainers"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainee not found")
            }
    )
    ResponseEntity<List<TrainerBriefDto>> getUnassignedActiveTrainers(
            @PathVariable String username
    );

    @PutMapping("/{username}/trainers")
    @Operation(
            summary = "Update assigned trainer list",
            description = "Replaces trainee's trainer list with a new list of trainer usernames.",
            parameters = @Parameter(
                    name = "username",
                    description = "Trainee username",
                    required = true
            ),
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "List of trainer usernames",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            array = @ArraySchema(
                                    schema = @Schema(type = "string", description = "Trainer username")
                            ),
                            examples = {
                                    @ExampleObject(
                                            name = "SampleUsernames",
                                            value = "[\"john.Doe\", \"jane.Smith\"]"
                                    )}
                            )
            ),
            responses = {
                    @ApiResponse(responseCode = "200", description = "Trainer list updated"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainee or trainer not found")
            }
    )
    ResponseEntity<List<TrainerBriefDto>> updateTraineeTrainersList(
            @PathVariable String username,
            @NotEmpty @RequestBody List<String> trainers
    );
}
