package com.epam.infrastructure.controllers;

import com.epam.infrastructure.dtos.TrainerDto;
import com.epam.infrastructure.dtos.TrainerRegistrationRequest;
import com.epam.infrastructure.dtos.TrainerResponseDto;
import com.epam.infrastructure.dtos.AuthDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping("/trainers")
@Tag(name = "Trainer Management", description = "Trainer registration and profile management endpoints")
public interface TrainerController {

    @PostMapping
    @Operation(
            summary = "Register new trainer",
            description = "Creates a new trainer profile and returns autogenerated username and password.",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Trainer registration data",
                    required = true,
                    content = @Content(schema = @Schema(implementation = TrainerRegistrationRequest.class))
            ),
            responses = {
                    @ApiResponse(responseCode = "201", description = "Trainer successfully registered"),
                    @ApiResponse(responseCode = "400", description = "Invalid input")
            }
    )
    ResponseEntity<AuthDto> register(
            @Valid @RequestBody TrainerRegistrationRequest trainer
    );


    @PutMapping
    @Operation(
            summary = "Update trainer profile",
            description = "Updates trainer personal info and active status. Specialization is read-only.",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Updated trainer information",
                    required = true,
                    content = @Content(schema = @Schema(implementation = TrainerDto.class))
            ),
            responses = {
                    @ApiResponse(responseCode = "200", description = "Trainer profile updated"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainer not found")
            }
    )
    ResponseEntity<TrainerResponseDto> updateProfile(
            @Valid @RequestBody TrainerDto trainer
    );


    @GetMapping("/{username}")
    @Operation(
            summary = "Get trainer profile",
            description = "Returns full trainer profile along with assigned trainees.",
            parameters = {
                    @Parameter(
                            name = "username",
                            description = "Username of the trainer",
                            required = true
                    )
            },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Trainer profile retrieved"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized access"),
                    @ApiResponse(responseCode = "404", description = "Trainer not found")
            }
    )
    ResponseEntity<TrainerResponseDto> getProfile(@PathVariable String username);
}
