spring:
  config:
    activate:
      on-profile: stg
  custom-datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gym_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:4999}
    driver-class-name: org.postgresql.Driver

hibernate:
  hbm2ddl:
    auto: update
  highlight_sql: true

app:
  kafka:
    topics:
      workload-events: trainer.workload.events.test

logging:
  level:
    root: info
    org.springframework.security: debug

system:
  admin:
    username: admin
    password: admin